title: Researcher
url: "https://ankitsultana.com"
baseurl: "/researcher"

markdown: kramdown
ins_logo: "./xmu.pdf"

tracking_id: #

footer: yes
footer_url: "https://github.com/Philoso0"
footer_text: "Page design by Philoso"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
