title: Zhe Liao (廖 哲)
url: "https://phyn-l.github.io"
baseurl: "/zliao"

remote_theme: ankitsultana/researcher@gem
markdown: kramdown
ins_logo: "./xmu.pdf"

tracking_id: #

footer: yes
footer_url: "https://github.com/Philoso0"
footer_text: "Page design by Philoso"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
